name: Check code style

on:
  [ push, pull_request ]

jobs:
  style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements

        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt
          python -m pip list

      - name: Install pre-commit
        run: |
          pre-commit install

      - name: Run mypy
        run: |
          python -m mypy ./project
          python -m mypy ./tests
